### ISSUE TITLE
create log model/serializer

### ISSUE THREAD

**Issue by Walrussuit101** [YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-backend#20]
We'll still keep the raw files for the visualization.
But for other data the website needs to graph it looks like a better route to parse and keep in the database.

**Branch: feature/logModelSerial**
- [x] Add objects into sys diagram from photos in drive
- [x] Make models in core/models
- [x] Make serializers as well in core/serializers/serializer.py

**Comment by Rithonn** [comment]
Photos for the db have been upload to the drive.

**Comment by Walrussuit101** [comment]
Sys diagram updated
