### ISSUE TITLE
Issue viewing the headings in the edit tab

### ISSUE THREAD

**Issue by cbrandt6** [YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-backend#75]
Headings are not being displayed properly in the edit tab of an entry. Only one heading is being displayed, and it seems to be the last heading that was created.

**Comment by Walrussuit101** [comment]
Fixed in [this](https://github.com/YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend/pull/107/commits/890545ca344a47deb7a1ed10561ef55538a78073) commit. Added it to the `feature/changeViewing` PR in frontend repo.
